# Generated by Django 4.2.1 on 2023-05-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
