# Generated by Django 4.2.1 on 2023-05-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0002_rename_questions_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_field',
            new_name='pub_date',
        ),
    ]
